ALTER TABLE ordenes ADD COLUMN IF NOT EXISTS cliente_nombre TEXT;
ALTER TABLE ordenes ADD COLUMN IF NOT EXISTS servicio_nombre TEXT;
ALTER TABLE ordenes ADD COLUMN IF NOT EXISTS precio_unitario DECIMAL(10,2);
ALTER TABLE ordenes ALTER COLUMN cliente_id DROP NOT NULL;
ALTER TABLE ordenes ALTER COLUMN servicio_id DROP NOT NULL;
